((nil . ((project-vc-name . "Walheimat")
         (find-sibling-rules . (("test/\\([^/]+\\)-test.el" "wal/\\1.el")
                                ("wal/\\([^/]+\\).el" "test/\\1-test.el")))
         (consult-buffer-filter . ("\\` " "\\`\\*" "\\`magit"))))
 (markdown-mode . ((eval . (auto-fill-mode t)))))
