#!/bin/bash

TEST_DIR="$(dirname "$(realpath "$0")")"

emacs -batch -l ert \
      -l "$TEST_DIR"/test-helpers.el \
      -l "$TEST_DIR"/test-list-manipulation.el \
      -f ert-run-tests-batch-and-exit
