* Style Guide

To increase readability, I'll try to unify how things are generally
structured.

** =use-package=

*** Keyword Order

The order is:

1. Conditional
   1. =if=
   2. =mode=
2. Configuration
   1. =init=
   2. =config=
3. Bindings
   1. =bind-keymap=
   2. =bind=
   3. =wal-bind=
   4. =general=
4. Loader order
   1. =hook=
   2. =defer= or =demand=
   3. =after=
   4. =commands=
5. Ensuring
   1. =ensure=
   2. =ensure-system-package=
   3. =load-path=
6. Delighting/Diminishing
   1. =delight=
   2. =diminish=

*** Single Line vs. Body

Singe lines make sense for =defer=, =after=, =ensure= and =hook= (if there's just one).

*** What Goes Into =config=?

Any immediately understood function calls are fine, non-obvious =mapc=
calls should be wrapped in their own =wal/configure-<package-name>=
functions.

** Commits

Commits are linted using =commitlint=. To set this up, load or require
package =wal-setup.el= and run =wal/setup-commit-hooks=.

The rules are defined in =commitlint.config.js= and a description of all
rules can be found [[https://commitlint.js.org/#/reference-rules][here]].
