name: test
on:
  push:
    branches:
      - trunk

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: get-emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.1
      - name: setup
        run: emacs --batch ./templates/init.el
      - name: test
        run: ./run-tests
