name: Test custom functions
on:
  push:
    branches:
      - trunk
      - feature/ci
    paths:
      - 'README.org'
      - 'setup/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Build
      - name: Get Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.1

      # Setup
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Tangle the configuration
        run: emacs --batch -l $GITHUB_WORKSPACE/setup/wal-setup-ci.el

      - name: Verify packages
        run: ls -al $GITHUB_WORKSPACE/wal

      # Use
      - name: Run the tests
        run: ./tests/run-tests
