name: test
on:
  push:
    branches:
      - trunk

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.1

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Tangle the configuration
        run: emacs --batch -l $GITHUB_WORKSPACE/setup/wal-setup-ci.el

      - name: Verify packages
        run: ls -al $GITHUB_WORKSPACE/wal

      - name: Run the tests
        run: ./run-tests
