name: Run tests
on:
  push:
    branches:
      - trunk
      - feature/cask
    paths-ignore:
      - 'assets/**'
      - 'etc/**'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'
      - 'commitlint.config.js'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment to allow unsecure commands
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Get Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.1

      - name: Get Cask
        uses: conao3/setup-cask@master
        with:
          version: 0.8.6

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Tangle the configuration
        run: emacs --batch -l ./setup/wal-setup-ci.el

      - name: Install
        working-directory: ./wal
        run: cask install

      - name: Run tests
        working-directory: ./wal
        run: cask exec ert-runner
