name: Verify
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'assets/**'
      - 'data/**'
      - 'README.org'
      - '.dir-locals.el'
      - 'CHANGELOG.md'
      - '.gitignore'
      - 'package.json'
      - 'package-lock.json'
      - 'proselintrc.json'
      - 'commitlint.config.js'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment to allow unsecure commands
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Get Emacs
        uses: purcell/setup-emacs@master
        with:
          version: release-snapshot

      - name: Get Cask
        uses: conao3/setup-cask@master
        with:
          version: 0.8.8

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Tangle and install dependencies with Cask
        run: make ci

      - name: Run tests
        run: make test

      - name: Submit coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run byte-compiler check (allowed to fail)
        continue-on-error: true
        run: make pacify

      - name: Simulate cold boot
        if: contains(github.event.head_commit.message, 'release')
        run: make cold-boot
